backend:
  name: github
  repo: giopunt/artebella

media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    label: News
    folder: news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Draft, name: draft, widget: boolean, default: true }
      - { name: path, label: Path }
      - { name: hero, label: Hero, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: excerpt, label: Excerpt, widget: text }
      - { name: body, label: Body, widget: markdown }